version: '3'


volumes:
  hureru_button_db:

services:

# フロントエンドさん
  hureru_button:
    image: node:16.16.0-alpine3.16
    restart: always
    user: ${NODE_USER}
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'yarn start'
    tty: true

# APIさん
  hureru_button_api:
    build: ./api
    depends_on:
    - hureru_button_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # .env
      - ADDRESS_BASE=${ADDRESS_BASE}
    volumes:
      - ./api/app:/go/src/app
      - ./voice:/go/src/app/voice
    tty: true
    command: go run main.go

# DBさん
  hureru_button_db:
    image: mariadb
    restart: always
    volumes:
      - hureru_button_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # .envファイルに環境変数を設定
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # .envファイルに環境変数を設定
      - MYSQL_DATABASE=hureru_voice
      - MYSQL_USER=hureru
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

# リバースプロキシさん
  reverse-proxy:
    image: nginx
    restart: always
    volumes:
      - ./rev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
