version: '3'

services:
  hureru_button:
    image: node:alpine3.16
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - type: bind
        source: ./voice
        target: /data/voice
    command: sh -c 'cat /data/voice/test.txt'
    ports:
      - '3000:3000'
    tty: true
