version: '3'


volumes:
  hureru_button_db:

services:
#   hureru_button:
#     image: arm64v8/node:18.6.0-alpine3.16
#     restart: always
#     environment:
#       - NODE_ENV=${NODE_ENV}
#     volumes:
#       - type: bind
#         source: ./voice
#         target: /data/voice
#     command: sh -c 'cat /data/voice/test.txt'
#     ports:
#       - '3000:3000'
#     tty: true

  hureru_button_api:
    build: ./api
    depends_on:
    - hureru_button_db
    restart: always
    volumes:
      - ./api/app:/go/src/app
    tty: true

  hureru_button_db:
    image: mariadb
    restart: always
    volumes:
      - hureru_button_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # .envファイルに環境変数を設定
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # .envファイルに環境変数を設定
      - MYSQL_DATABASE=hureru_voice
      - MYSQL_USER=hureru
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - 9700:3306



    

  
