version: '3'


volumes:
  hureru_button_db:

services:

# フロントエンドさん
  hureru_button:
    image: node:16.16.0-alpine3.16
    # user: ${NODE_USER}
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    command: sh -c 'yarn start'
    tty: true

# APIさん
  hureru_button_api:
    build: ./api
    depends_on:
    - hureru_button_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # .env
      - ADDRESS_BASE=${ADDRESS_BASE}
    volumes:
      - ./api/app:/go/src/app
      - ./voice:/go/src/app/voice
      - ./yaml:/go/src/app/yaml
    tty: true
    command: go run main.go

# DBさん
  hureru_button_db:
    image: mariadb
    restart: always
    volumes:
      - hureru_button_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # .envファイルに環境変数を設定
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # .envファイルに環境変数を設定
      - MYSQL_DATABASE=hureru_voice
      - MYSQL_USER=hureru
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

# リバースプロキシさん
  reverse-proxy:
    image: nginx
    restart: always
    depends_on:
      - hureru_button_api
      - hureru_button
    volumes:
      - ./rev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

# # とりあえず入れる音楽データを加工するようコンテナ
#   voiceinserter:
#     build: ./voiceinserter
#     environment:
#     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # .envファイルに環境変数を設定
#     - MYSQL_DATABASE=hureru_voice
#     volumes:
#       - ./voice:/usr/src/app/voice
#       - ./voiceinserter/src:/usr/src/app
#     command: python3 main.py
  